name = "damp-block-c720"
main = "src/index.ts"
compatibility_date = "2025-09-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./public"

[observability]
enabled = true

# Durable Objects
[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]

# D1
[[d1_databases]]
binding = "mathiks_db"
database_name = "mathiks-db"
database_id = "1defe692-9700-4d02-94b9-49d8a6e98d39"
preview_database_id = "1defe692-9700-4d02-94b9-49d8a6e98d39"

# Queues
[[queues.producers]]
binding = "mathiks_jobs"
queue = "mathiks-jobs"

[[queues.consumers]]
queue = "mathiks-jobs"

# Hyperdrive
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "432028a0868947689575f188be8f59cf"
# localConnectionString = "postgresql://user:pass@localhost:5432/db"

